### ISSUE TITLE
RemoteConfigService 中的getInstance虽然使用了双重锁定也不一定线程安全吧？

### ISSUE THREAD

**Issue by fangjieDevp** [Meituan-Dianping/Zebra#12]

**Comment by deqianzou** [comment]
> _No description provided._

`public static RemoteConfigService getInstance() {
		return ConfigServiceHolder.configService;
	}`

	`private static class ConfigServiceHolder {
		private static RemoteConfigService configService = new RemoteConfigService();
		static {
			ConfigServiceHolder.configService.init();
		}
	}`
大概这样会好一些吧？
