### ISSUE TITLE
mvn仓库更新不了，给个镜像地址

### ISSUE THREAD

**Issue by zhaoyongsheng** [Meituan-Dianping/Zebra#19]
mvn仓库更新不了，给个镜像地址

**Comment by 8wy1985659** [comment]
更新不了什么意思 有jar包拉不下来？

**Comment by 8wy1985659** [comment]
http://unidal.org/nexus/service/local/repositories/releases/content/com/dianping/zebra/zebra-client/2.9.1/zebra-client-2.9.1.jar
http://unidal.org/nexus/service/local/repositories/releases/content/com/dianping/zebra/zebra-cat-client/2.9.1/zebra-cat-client-2.9.1.jar
http://unidal.org/nexus/service/local/repositories/releases/content/com/dianping/zebra/zebra-dao/0.2.1/zebra-dao-0.2.1.jar

**Comment by zhaoyongsheng** [comment]
收到，我下午找到这个镜像源站了。

**Comment by zhaoyongsheng** [comment]
能微信群拉我一下吗，加不进去345903562。

**Comment by 8wy1985659** [comment]
> 345903562

https://github.com/Meituan-Dianping/Zebra/wiki/WeChat%E4%BA%A4%E6%B5%81%E7%BE%A4

扫码进群哈
