### ISSUE TITLE
statement getUpdateCount记录更新行数含义不对

### ISSUE THREAD

**Issue by RongNanNan** [Meituan-Dianping/Zebra#24]
getUpdateCount应该是多结果集时用到，常规更新应该还是-1，或是调用内部持有的statement的getUpdateCount

**Comment by 8wy1985659** [comment]
现在单库更新的影响行数计算方式就是计算内部持有的statement的getUpdateCount

**Comment by RongNanNan** [comment]
并不是，而是把更新行数记下来作为返回数据返回的

**Comment by 8wy1985659** [comment]
zebra的逻辑在单库上sql是串行执行的 如果查单表 那么就相当于返回单个statement的affectedRows 如果查多表那么把多表的affectedRows聚合返回 语义上应该没有问题

**Comment by 8wy1985659** [comment]
明白你意思了 这里我调整一下

**Comment by 8wy1985659** [comment]
修改已经提交了
https://github.com/Meituan-Dianping/Zebra/commit/5baf3f05fbf6ef38918bae7077779d45f4b20d84
另外请教下是否有在使用中遇到返回-1的case
