### ISSUE TITLE
XXE漏洞

### ISSUE THREAD

**Issue by 360CodeSafe** [Meituan-Dianping/Zebra#25]
您好：
我是360代码卫士的工作人员，在我们的开源项目代码审计过程中，发现Zebra多处处理xml数据时没有禁用外部实体。详细信息如下：
在Zebra-master\zebra-admin-web\src\main\java\com\dianping\zebra\administrator\util\JaxbUtils.java文件中的jaxbReadXml方法中
![default](https://user-images.githubusercontent.com/39950310/51169440-dcf37c00-18e6-11e9-8f9b-2d88381057c8.png)
该方法是将xml转化为java，在JdbcrefController.java文件的findJdbcrefDetil方法中调用了该函数
![default](https://user-images.githubusercontent.com/39950310/51169585-3b205f00-18e7-11e9-8171-4eeaf819cb50.png)
groupValue变量是从数据库中取的，用户可以通过插入任意值来进行xxe攻击（由于项目我也没搭建起来，不敢百分百确认，这个需要你们确认下）。

同样的问题也存在于
Zebra-master\zebra-client\src\main\java\com\dianping\zebra\util\JaxbUtils.java  43行
Zebra-master\zebra-client\src\main\java\com\dianping\zebra\group\config\datasource\transform\DefaultSaxParser.java    81行
Zebra-master\zebra-client\src\main\java\com\dianping\zebra\group\config\system\transform\DefaultSaxParser.java     85行

**Comment by nanolikeyou** [comment]
实际上groupValue并非来自于数据库，byte流是来自于zooKeeper.getData获取节点数据内容是可信的。而要触发zk操作还可调用ZookeeperService.setConfig 。但是这里类型转化验证，会抛出org.apache.zookeeper.KeeperException$ConnectionLossException
另外一处findRuleName也是同样的情况，所以标记为无触发污染点的误报。
