### ISSUE TITLE
Zebra相比shardingJDBC 解决了什么问题

### ISSUE THREAD

**Issue by jingb** [Meituan-Dianping/Zebra#26]
问一个不成熟的问题，shardingJDBC已经算是久经考验的中间件了，18年也进了Apache，发展的挺好。那zebra是为了解决一些什么痛点问题而发开的呢，还是更多为了适配大众点评自己的业务？另，zebra-dao提供的RowBoundsWithCallback和RowBoundsWithFuture，可以理解成是异步的JDBC么

**Comment by xiaotongtj** [comment]
1

**Comment by ainilife** [comment]
1. zebra在美团点评是2014年开发的中间件，比shardingjdbc时间更早。经过美团点评全公司全覆盖使用这么多年，也是久经考验的中间件了。
2. zebra-dao部分功能是异步化dao的功能，还不止于此，比如和cat整合进行监控和打点等功能。
