### ISSUE TITLE
zebra-dao 可以单独使用嘛？

### ISSUE THREAD

**Issue by zohar-soul** [Meituan-Dianping/Zebra#27]
因为目前用的到的只有mybatis异步查询这一块。

**Comment by ainilife** [comment]
可以的。试试看。

**Comment by zohar-soul** [comment]
@ainilife 谢谢，顺便问一下，我看zebra最初的版本就是16年还没合并到dinping仓库的版本中。mybatis异步查询是通过自己建立线程池来实现的。
那么如果这样的话，如果较多请求进来的话，这个线程池要么线程数很多，要么等待，
相当于本来是tomcat线程大量增加 or 阻塞，变成了这个sql查询的地方受限，因为jdbc用的还是同步的，
那么相当于servlet调用查询数据库的线程在做完其他事情后还是要等待数据的返回？
那这样的话，异步化的效果明显吗？
谢谢大佬啦。

**Comment by ainilife** [comment]
你说的异步化的问题很好。点评内部的实践是从上到下全部异步化了，也就是rpc->db整个链路做了异步化，效果明显，简单的服务可以跑到单机接近1WQPS了。

**Comment by zohar-soul** [comment]
@ainilife 
谢谢
