### ISSUE TITLE
打的zebra-client的包druid的有疑问

### ISSUE THREAD

**Issue by RongNanNan** [Meituan-Dianping/Zebra#28]
打出来zebra-client的包里面包含了druid的内容，但是没有修改包名，这样的话没有太大的作用
而且分库分表本身就会使用druid的语法分析等，而且新老版本兼容问题，该处还是改写包名，依赖一个固定版本的druid，另druid的版本太低，有些bug都修复了，但是依赖新的druid对分库分表有影响
![image](https://user-images.githubusercontent.com/19367620/51956919-75136880-2484-11e9-85cb-9920ba1cf78b.png)

**Comment by 8wy1985659** [comment]
打包使用maven-shade-plugin插件 打包后不影响业务版本使用
代码在https://github.com/Meituan-Dianping/Zebra/blob/master/zebra-client/pom.xml 可以看下

**Comment by RongNanNan** [comment]
shade的插件我看到了，但是里面的设置就是把druid的东西打进去了而已包名没有修改，这就会造成如果业务方已经依赖druid，可能会造成冲突，例如里面有2个DruidDataSource

**Comment by ainilife** [comment]
嗯，是个好问题，我们想办法解决下。

**Comment by 8wy1985659** [comment]
shade打包之后使用zebra应该是会优先加载zebra包里的durid 理论上和业务的版本应该不会冲突 这个我再测试下 不行的话换一种方式解决这个问题
