### ISSUE TITLE
catFilter参数打印问题

### ISSUE THREAD

**Issue by RongNanNan** [Meituan-Dianping/Zebra#29]
catFilter打印sql参数时，List<ParamContext>

**Comment by RongNanNan** [comment]
catFilter打印sql参数时，List<ParamContext>，是按照list的顺序打印，并不是按照真实parameterIndex的位置打的，如果set参数不是按照顺序的化，打印的有问题

**Comment by 8wy1985659** [comment]
已修复 
https://github.com/Meituan-Dianping/Zebra/commit/f2f750f4ae55ebd6305ff6bc5e759cf83728b251

**Comment by RongNanNan** [comment]
e，（？，？，？）调用：setString(3, '3')再setString(2, '2')再setString(1, '1')不会报错？

**Comment by RongNanNan** [comment]
使用Set记录实现Comparable，或是提供比较器给外面
	private static Comparator<ParamContext> PARAM_COMPARATOR = new Comparator<ParamContext>(){
		@Override
		public int compare(ParamContext paramContext1, ParamContext paramContext2) {
			return paramContext1.getIndex() - paramContext2.getIndex();
		}
	};

**Comment by 8wy1985659** [comment]
从使用方式上来讲 先setString(3, '3')再setString(2, '2')再setString(1, '1') 并不是必要需求
与其最后去compare 不如在插入时限定好顺序 我是这样理解的

**Comment by RongNanNan** [comment]
我们的想法可能不一样，我的理解就是参数的打印顺序必须和sql里面的占位的顺序完全一致，而且没有文档标注必须按顺序进行参数设置，只要设置完全即可

另，如果不认同这个观点的话，建议还是不要修复了（交由别人的内部版本视情况修改），否则还会导致错误

**Comment by 8wy1985659** [comment]
2种方案都可以保证打印顺序 不过开源版本确实应该考虑好兼容性 这里我同意你的观点 
不过从实际使用上来讲 我确实觉得没有必要过于灵活

**Comment by ainilife** [comment]
这个问题不大。按照你的这个要求去实现有点复杂，建议还是保持现状。无伤大雅。
