### ISSUE TITLE
你们开源了Zebra和DBProxy，公司内部应用是咋分工的，两个一起用？那个性能更好，有测试过吗？

### ISSUE THREAD

**Issue by y123456yz** [Meituan-Dianping/Zebra#30]
你们开源了Zebra和DBProxy，公司内部应用是咋分工的，两个一起用？那个性能(包括tps、时延等)更好，有测试过吗？
谢谢

**Comment by y123456yz** [comment]
@ainilife

**Comment by 8wy1985659** [comment]
1. DBProxy是服务端代理方案  Zebra是客户端代理方案 Zebra目前是公司主推的方案 java应用统一使用Zebra  DBProxy目前主要支持一些使用小语种开发的应用。
2.中间件本身耗时的比较我们没有测试过，相较于在调用链路上相较于网络通信的耗时，中间件本身性能上的差异微乎其微，Zebra直连数据库相较于DBProxy节省了3层网络开销,测试时整体性能提升超过30%。同时由于省略了DNS MGW 数据库代理 等中间节点，避免了因中间节点问题导致不可用的情况，大幅提升整体可用性。

**Comment by y123456yz** [comment]
@8wy1985659  
那我明白了，你们这个是部署在所有业务方机器上面，然后直连数据库？是这意思。
和dbproxy的区别就是，省掉了中间一层。
直白点，就是java业务你们内部用zebra，其他语言用dproxy。

**Comment by 8wy1985659** [comment]
对的

dbproxy内部基本不开发了
