### ISSUE TITLE
zebra如何支持mysql的迁移、扩容方案

### ISSUE THREAD

**Issue by wangdongyun** [Meituan-Dianping/Zebra#43]
我有两个问题:
迁移：
1. zebra如何支持mysql的主库、从库的迁移。

扩容：
 在分库分表的方案中，zebra是如何支持扩容的，这里面可能有两个方面
1. 不更改库表的个数，迁移库，如何支持在线 `更改路由`
2. 如果库、表的个数初始估计不足，后期如何扩容、迁移数据。

**Comment by 8wy1985659** [comment]
迁移：主库迁移一般在MHA切换后修改主库url，通过配置动态刷新将流量改到新的主库
           从库迁移数据同步完成后把心从库节点上线，老从库节点下线即可，也是通过动态刷新完成
扩容：1.迁库同上面的迁移方案 数据库迁移完成后把zebra配置中的url改掉即可
           2.这个问题跟适用方规则设计有关，
               (1)使用方设计如果是简单的使用hash均摊数据，一般的操作就是搭一套新集群重新划分流量同步，等新集群数据追上老集群再停服切换。
               (2)使用方预留了未来新的分表键逻辑，在规则上允许数据分布不均匀，这时候可以在业务层操作生成新的分表id，根据规则自动路由到新库，避免数据重新划分，就不需要迁移数据了。

**Comment by wangdongyun** [comment]
\(^o^)/~ 

Thanks.
