### ISSUE TITLE
zebra-admin-web:delete zookeeper config error

### ISSUE THREAD

**Issue by stancycowen** [Meituan-Dianping/Zebra#73]
fail to delete config from zookeeper due  to error code :
https://github.com/Meituan-Dianping/Zebra/blob/master/zebra-admin-web/src/main/java/com/dianping/zebra/administrator/service/impl/JdbcrefServiceImpl.java
line 80

**Comment by Dapjeanqnea** [comment]
the same error. Successfully deleted the data in the database, but the zk did not delete

**Comment by stancycowen** [comment]
> the same error. Successfully deleted the data in the database, but the zk did not delete

LOL...

**Comment by 8wy1985659** [comment]
develop分支已经修复了 可以切个分支使用
